---
# general windows deploy 
working_dir: 'C:\Temp\Working\Ansible'
wallpaper_dir: 'C:\Wallpaper'
choco_server_source: "internal_repo"

# windows_deploy_dns_server
win_deploydnsserver_forwarders:
  - "1.1.1.1"
win_deploydnsserver_working_dir: "{{ working_dir }}"

# Ansible variables
ansible_connection: psrp
ansible_psrp_cert_validation: ignore
ansible_psrp_protocol: https
ansible_psrp_auth: ntlm
ansible_psrp_credssp_auth_mechanism: ntlm
ansible_become_method: runas