- name: Add grayteam User to Enterprise Admin Group
  community.windows.win_domain_group_membership:
    name: "{{ item }}"
    members:
      - grayteam
    state: present
  loop:
    - "Enterprise Admins"
    - "Domain Admins"
    - "Remote Management Users"
