---
# The playbook for CDT 3

# //\\//\\// MGMT \\//\\//\\//\\

# - hosts: dns:choco
#   roles:
#     - windows_deploy_standards
#   tags:
#     - never
#     - mgmt
#     - mgmt_win
#     - mgmt_deploy_standards

# - hosts: dns
#   roles:
#     - windows_deploy_dns_server
#   tags:
#     - never
#     - mgmt
#     - mgmt_win
#     - mgmt_dns

# - hosts: choco
#   roles:
#     - windows_deploy_chocolatey_server
#   tags:
#     - never
#     - mgmt
#     - mgmt_win
#     - mgmt_choco

# //\\//\\// MGMT \\//\\//\\//\\

# //\\//\\/\\//\\ Windows //\\//\\/\\//\\

# name: run windows deploy standards
- name: Run Windows Standards
  hosts: windows:&team_hosts
  roles:
    - windows_deploy_standards
  tags:
    - never
    - team
    - windows
    - team_deploy_standards

# install extras for windows machines
# - name: Windows Extra
#   hosts: windows:&team_hosts
#   roles:
#     - windows_extras
#   tags: 
#     - never
#     - team
#     - windows
#     - team_win_extras

#deploy dc and create dns records
- name: Deploy DC and create Domain
  hosts: arboretum
  roles:
    - windows_deploy_dc
    - windows_deploy_dns_server
  tags:
    - never
    - team
    - windows
    - team_deploy_dc

# create local users and join domain
- name: Join boxes to Domain
  hosts: windows:&team_hosts:!arboretum:!sternwood
  roles:
    - windows_create_local_users
    - windows_join_domain
  tags:
    - never
    - team
    - windows
    - team_join_ad_win

# - name: Deploy SMB Share
#   hosts: salsaritas
#   roles: 
#     - windows_deploy_smb
#   tags: 
#     - never
#     - team
#     - windows
#     - team_deploy_smb

# installing chrome
# - name: Install Chrome
#   hosts: windows:&team_hosts
#   roles: 
#     - windows_deploy_iis
#   tags:
#     - chrome
#     - windows

# post deploy cleanup // RUN ONLY WHEN FINISHED WITH DEPLOY
# - name: Post deploy standards
#  hosts: windows:&team_hosts
#  roles:
#    - windows_post_deploy
#  tags:
#    - never
#    - windows_post_deploy

# //\\//\\/\\//\\ Windows //\\//\\/\\//\\
