---
- name: Disable first logon screen
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableFirstLogonAnimation
    data: 0
    type: dword

- name: Reboot the machine with all defaults
  ansible.windows.win_reboot:  