---
# - name: Copy Over iis
#   ansible.windows.win_copy:
#     src: files/nop.zip
#     dest: "{{ win_deploy_iis_working_dir }}/nop.zip"

- name: Copy Over index.html
  ansible.windows.win_copy:
    src: files/index.html
    dest: C:\inetpub\wwwroot\

- name: Remove default htm file
  ansible.windows.win_file:
    path: C:\inetpub\wwwroot\iisstart.htm
    state: absent

- name: Copy Over Gaia
  ansible.windows.win_copy:
    src: files/Gaia.jpg
    dest: C:\inetpub\wwwroot\

- name: Remove default png
  ansible.windows.win_file:
    path: C:\inetpub\wwwroot\iisstart.png
    state: absent

# - name: Unzip nop.zip
#   community.windows.win_unzip:
#     src: "{{ win_deploy_iis_working_dir }}/nop.zip"
#     dest: C:\inetpub\wwwroot\iis\
#     creates: C:\inetpub\wwwroot\iis\

- name: "Give DefaultAppPool File Access"
  ansible.windows.win_acl:
    path: C:\inetpub\wwwroot\
    user: IIS AppPool\DefaultAppPool
    rights: Read,Write,Modify,FullControl,Delete
    type: allow

- name: Create IIS Site
  community.windows.win_iis_website:
    name: delos
    state: started
    port: 80
    ip: '*'
    hostname: "{{ inventory_hostname }}"
    application_pool: DefaultAppPool
    physical_path: C:\inetpub\wwwroot\
  register: output

# - name: Install iis Via Selenium
#   ansible.windows.win_command: "python {{ win_deploy_iis_working_dir }}/main.py"
#   when: output.changed
#   become: yes
#   become_user: whiteteam
#   become_method: runas
#   async: 120
#   ignore_errors: yes
