---
all:
  vars:
    #default values for the variables
    subbnet_ish: "PlaceHolder"
    host_octets: "PlaceHolder"
    team_number: "PlaceHolder"
    children:
      #hosts
      # LAN Hosts
      claws:
        vars:
          ansible_host: "10.{{ team_number|int }}.1.1"
          host_octets: "1"
        hosts:
          claws.team[01:02].rit.local:
      salsaritas:
        vars:
          ansible_host: "10.{{ team_number|int }}.1.2"
          host_octets: "2"
        hosts:
          salsaritas.team[01:02].rit.local:
      daryll-laptop:
        vars:
          ansible_host: "10.{{ team_number|int }}.1.3"
          host_octets: "3"
        hosts:
          daryll-laptop.team[01:02].rit.local:
      mycourses:
        vars:
          ansible_host: "10.{{ team_number|int }}.1.4"
          host_octets: "4"
        hosts:
          mycourses.team[01:02].rit.local:
      cyber-range:
        vars:
        ansible_host: "10.{{ team_number|int }}.1.5"
        host_octets: "5"
        hosts:
            cyber-range.team[01:02].rit.local:
      
  #Cloud
      sis:
        vars:
          ansible_host: "10.{{ team_number|int }}.2.1"
          host_octets: "5"
        hosts:
            sis.team[01:02].rit.local:
      munson-laptop:
        vars:
          ansible_host: "10.{{ team_number|int }}.2.2"
          host_octets: "5"
        hosts:
            munson-laptop.team[01:02].rit.local:
      banjo:
        vars:
          ansible_host: "10.{{ team_number|int }}.2.3"
          host_octets: "5"
        hosts:
            banjo.team[01:02].rit.local:
      vase:
        vars:
          ansible_host: "10.{{ team_number|int }}.2.4"
          host_octets: "5"
        hosts:
            vase.team[01:02].rit.local:

      windows:
        children:
          #lan
          claws:
          salsaritas:
          daryll-laptop:
          #cloud
          sis:
          munson-laptop:

      linux:
        children:
          #lan
          mycourses:
          cyber-range:
          #cloud
          banjo:
          vase:

      team_hosts:
        vars:
          no_dns: False
        children:
          #lan
          claws:
          salsaritas:
          daryll-laptop:
          mycourses:
          cyber-range:
          #cloud
          sis:
          munson-laptop:
          banjo:
          vase:

      lan:
        vars:
          subbnet_ish: "10.{{ team_number|int}}.1."
        children:
          claws:
          salsaritas:
          daryll-laptop:
          mycourses:
          cyber-range:

      cloud:
        vars:
          subbnet_ish: "10.{{ team_number|int}}.2."
        children:
          sis:
          munson-laptop:
          banjo:
          vase: