- name: Create directory structure
  ansible.windows.win_file:
    path: C:\Troy
    state: directory

- name: Add team share
  ansible.windows.win_share:
    name: "Golden Fleece"
    description: "Team Share"
    path: C:\Troy
    list: yes
    full: Administrators
    read: Everyone

- name: Create and copy score check file to team share
  ansible.windows.win_copy:
    src: files/sparta.txt
    dest: C:\Troy\sparta.txt

- name: Create and copy score check file to team share
  ansible.windows.win_copy:
    src: files/info.txt
    dest: C:\Troy\info.txt

- name: Create and copy score check file to team share
  ansible.windows.win_copy:
    src: files/fleece.jpeg
    dest: C:\Troy\fleece.jpeg