- name: Create directory structure
  ansible.windows.win_file:
    path: C:\Tickets
    state: directory

- name: Add team share
  ansible.windows.win_share:
    name: "Salsa's"
    description: "Salsarita's Ticket Submission"
    path: C:\Salsa
    list: yes
    full: Administrators
    read: Everyone

- name: Create and copy score check file to team share
  ansible.windows.win_copy:
    src: files/sparta.txt
    dest: C:\Troy\sparta.txt